### ISSUE TITLE
Migrate to cmake

### ISSUE THREAD

**Issue by gunmetal313** [horsicq/DIE-engine#1]
Migrate to cmake?

**Comment by horsicq** [comment]
It seems like a good idea.

**Comment by gunmetal313** [comment]
my fork https://github.com/gunmetal313/DIE-engine

**Comment by horsicq** [comment]
Great!

**Comment by gunmetal313** [comment]
now finished yet.I say you,then i finish it.(Вы русский? :)  )

**Comment by horsicq** [comment]
Да. :)

**Comment by gunmetal313** [comment]
Исходников Gui нет на github?

**Comment by horsicq** [comment]
Нет. Но там ничего особо интересного нет.Самое главное выложено здесь, это движок сканирования и классы для работы с разными форматами. 
Я неспеша переписываю GUI под qt5. Как сделаю, то выложу на github.

**Comment by gunmetal313** [comment]
а ядро пока-что не переписываете на qt5?

**Comment by horsicq** [comment]
И ядро тоже. :)

**Comment by gunmetal313** [comment]
Мой друд не будет напрасным(cmake)? :)

**Comment by gunmetal313** [comment]
Кстати может прикрутить unut тесты? (и бинарники с проекта corcami) для тестирования?

**Comment by horsicq** [comment]
Труд не будет напрасным. :) Многие принципиально не хотят переходить на qt5 и пользуются qt4.

**Comment by horsicq** [comment]
Идея с corkami интересная. Надо будет попробовать.

**Comment by gunmetal313** [comment]
int DIELIB_API DIE_scanA(char *pszFileName, char *pszOutBuffer, int nOutBufferSize, unsigned int nFlags);


Вот как теперь выглядит :)

**Comment by horsicq** [comment]
Отлично. :)

**Comment by gunmetal313** [comment]
минимальная версия qt 5.3 наверно пусть будет...

**Comment by horsicq** [comment]
Ok.

**Comment by gunmetal313** [comment]
Миграция на cmake почти завершена :)

**Comment by gunmetal313** [comment]
ivan@ivan-pc:~/1git/DIE-engine/build$ ./diecmdd libnssutil3.so
ELF: library: GLIBC(2.4)[shared object 386-32]
ELF: compiler: gcc((GNU) 4.9.1)[shared object 386-32]
ivan@ivan-pc:~/1git/DIE-engine/build$ ./diecmdd Protobuild.exe
*** Error in `./diecmdd': free(): invalid pointer: 0x0861ec00 ***
Аварийный останов (сделан дамп памяти)
версия 0.95 с сайта и скомпилированная падают.(ubundu 32 битная...)Буду искать где проблема...

**Comment by horsicq** [comment]
Проблема скорее всего где-то в общих библиотеках.:(
