### ISSUE TITLE
Compilation overlap in lin64 build

### ISSUE THREAD

**Issue by deepio** [horsicq/DIE-engine#15]
I have built Qt5.6.3 on debian using source -> `https://github.com/qt/qt5.git` from commit `12fd0d5b9b486eaf80712d390265402a3bb06f0e`. I checked out the modules I think DIE-engine required to build? **qtsvg**, **qtxmlpatterns** maybe?, **qtscript**. But when I tried installing `DIE-engine` it failed complaining about a missing header file for windows. I think there might be something wrong with the build script? I'm trying to install DIE in a headless VM running debian, which might be related but does not obviously appear to be relevant at this time. 

```
root$ :/opt/DIE-engine# bash ./build_lin64.sh
Version: 2.06
rm -f moc__mainclass.cpp moc_scriptpe.cpp moc_scriptmsdos.cpp moc_scriptelf.cpp moc_scriptbinary.cpp moc_scan.cpp moc_pluginsscript.cpp moc_versionresource.cpp moc_pefile.cpp moc_msdosfile.cpp moc_elffile.cpp moc_textfile.cpp moc_binary.cpp moc_machfile.cpp moc_scriptmach.cpp moc_scripttext.cpp moc_scriptgeneric.cpp moc_singlefilescan.cpp
rm -f mainc.o _mainclass.o scriptpe.o scriptmsdos.o scriptelf.o scriptbinary.o scan.o utils.o pluginsscript.o versionresource.o pefile.o msdosfile.o elffile.o textfile.o binary.o machfile.o scriptmach.o scripttext.o scriptgeneric.o singlefilescan.o moc__mainclass.o moc_scriptpe.o moc_scriptmsdos.o moc_scriptelf.o moc_scriptbinary.o moc_scan.o moc_pluginsscript.o moc_versionresource.o moc_pefile.o moc_msdosfile.o moc_elffile.o moc_textfile.o moc_binary.o moc_machfile.o moc_scriptmach.o moc_scripttext.o moc_scriptgeneric.o moc_singlefilescan.o
rm -f *~ core *.core
g++ -c -pipe -Wno-missing-field-initializers -O2 -Wall -W -D_REENTRANT -fPIC -DDIE_CONSOLE -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../../Qt5.6/include -I../../../Qt5.6/include/QtScript -I../../../Qt5.6/include/QtXml -I../../../Qt5.6/include/QtCore -I. -I../../../Qt5.6/mkspecs/linux-g++ -o mainc.o mainc.cpp
In file included from mainc.cpp:26:
../singlefilescan.h:12:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2290: mainc.o] Error 1
```
I know there's a `__windows.h` file in the root of `DIE-engine`'s directory, maybe that's what it's looking for? If I include this file in the build it **seems** to compile correctly?
If I let it compile though, it eventually complains about a missing language directory? `cp: cannot stat '/opt/DIE-engine/die_source/lang': No such file or directory`. There is no lang folder in the die_source folder though? I must be missing something?

When I try running the precompiled release I get `./base/die: relocation error: ./base/die: symbol __cxa_throw_bad_array_new_length version Qt_5 not defined in file libQt5Gui.so.5 with link time reference`. So maybe i'm missing another qt module anyway?

**Comment by horsicq** [comment]
Hello! What version of Debian do you have?

**Comment by deepio** [comment]
Debian GNU/Linux 10 (buster)

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I made some fixes.

Could you try:

**git clone --recursive https://github.com/horsicq/DIE-engine.git
cd DIE-engine
bash -x build_lin64.sh**

**Comment by deepio** [comment]
That has fixed the lang issue, yes. There are other issues now but I don't think they are related to DIE-engine. I think it's with how I installed Qt, `{$QT}/lib/libicui18n.so.56.1` seems to be missing. 

Closing the issue, 260a7a59579450d67cc42e53451b206b03ce6b34 fixed it I think. Thank you
