### ISSUE TITLE
Visual Studio 2019 16.6.0 error C2039

### ISSUE THREAD

**Issue by extrimexxx** [horsicq/DIE-engine#16]
in new update Visual Studio 2019 16.6.0 compiler gives error
https://github.com/horsicq/DIE-engine/blob/7811e53cea200318247b8e6728b3cc704b5d959d/die_source/scan.cpp#L200
`..\scan.cpp(200): error C2039: "bRecursive": is not a member of "SpecAbstract::SCAN_OPTIONS".`

there was no error in the previous version Visual Studio 2019 16.5.5

**Comment by horsicq** [comment]
Thanks a lot fort the bugreport! I fixed it. You could just download again the sources and try again.

**git clone --recursive https://github.com/horsicq/DIE-engine.git**

**Comment by extrimexxx** [comment]
Thanks, compile done. And one more thing, submodule XQwt import QwtOpenGL, but build script `build_win32.bat` `build_lin64.sh` `build_mac.sh` no copy Qt5OpenGL.dll Qt5OpenGL.so QtOpenGL to folder `%SOURCE_PATH%\release\`
Thank You!

**Comment by horsicq** [comment]
Thanks! I'll fix the build scripts too!
