### ISSUE TITLE
Sorting by percentage is wrong

### ISSUE THREAD

**Issue by shuax** [horsicq/DIE-engine#18]
![image](https://user-images.githubusercontent.com/6940583/90227048-88a7d980-de46-11ea-9b47-71ab8fed77a5.png)

It seems to be sorted by string instead of float

**Comment by horsicq** [comment]
Thanks for the bugreport! It will be fixed in the next version.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
