### ISSUE TITLE
Missing libQt5OpenGL.so.5 on Ubuntu 20.04

### ISSUE THREAD

**Issue by ryanmkurtz** [horsicq/DIE-engine#19]
Running `die.sh` on **Ubuntu 20.04** results in:

`./base/die: error while loading shared libraries: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory`

Running `sudo apt install libqt5opengl5` takes care of the problem.  Perhaps you can bundle the missing library?

Thanks!

**Comment by horsicq** [comment]
Thanks a lot for the bugreport.
It will be fixed in the next version.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
