### ISSUE TITLE
More metadata in command line output

### ISSUE THREAD

**Issue by ryanmkurtz** [horsicq/DIE-engine#20]
Would it be possible to add more metadata to the output of `diec.sh`?  In particular, it would be great if the "Type" field (from the GUI) was added so we could see, for example, that a PE is of type _GUI_ or _DLL_.

**Comment by horsicq** [comment]
Good idea. I will add this information.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
