### ISSUE TITLE
Close button not working in MIME section. Requests.

### ISSUE THREAD

**Issue by murat5038** [horsicq/DIE-engine#25]
Problem: When the mime button is pressed, the "close" button function does not work.
**Request 1:** Text search box in Hex property can be added.
**Request 2:** Byte per line option can be added in Hex section.
**OS:** Windows 10 2004 build.
**DIE Version:** 3.01b

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! It will be fixed.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
