### ISSUE TITLE
Building 64bit version from source does not contain the executables

### ISSUE THREAD

**Issue by amarquez914** [horsicq/DIE-engine#26]
I have been trying to build the application from source but for some reason I am unable to get the exes created so far only this gets added to the zip file:

1. Qt5Core.dll
2. Qt5Gui.dll
3. Qt5Network.dll
4. Qt5OpenGL.dll
5. Qt5Script.dll
6. Qt5ScriptTools.dll
7. Qt5Svg.dll
8. Qt5Widgets.dll
9. db
10. imageformats
11. info
12. lang
13. listoffiles.txt
14. msvcp140.dll
15. msvcp140_1.dll
16. platforms
17. qss
18. vcruntime140.dll
19. vcruntime140_1.dll

Running the script for the win_64bit version ends up creating a zip file with no executable. I am using VS Community 2019, QT 5.15.2, and 7 zip. The scripts have the variables set correctly as well, not sure what could be causing this or where to look.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport!

I found this issue.

To avoid it try to compile 32 and 64 versions in a separate folders:

1) git clone --recursive https://github.com/horsicq/DIE-engine.git
2) copy DIE-engine to DIE-engine_32
3) copy DIE-engine to DIE-engine_64
4) run build_win32.bat in  DIE-engine_32
5) run build_win64.bat in  DIE-engine_64
