### ISSUE TITLE
MacOS Language not Changing

### ISSUE THREAD

**Issue by MaxTCodes** [horsicq/DIE-engine#27]
When I open up DIE on MacOS, it only is in Chinese. I've tried to change it in settings; however, it doesn't change. 

I just opened it up for the first time on my Mac. See [screenshot](https://doggo.ninja/IyRqFS.png).
I try changing the language to English. See [screenshot](https://doggo.ninja/TvNWLE.png).
I restarted the app, and it didn't change. see [screenshot](https://doggo.ninja/rnld6r.png).

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport! If you cannot change settings you opened DiE from readonly location. Just copy DiE.app from zip or mounted dmg to another folder.

**Comment by MaxThakurCodes** [comment]
I tried both of the methods. I put it in downloads then extracted it; I tried that. It doesn't seem to be working... I believe it's a bug within the code!

**Comment by horsicq** [comment]
Ok. I will take a look and fix it in the next version of DiE. Could you just remove die.app/contents/resources/lang ?

**Comment by MaxThakurCodes** [comment]
Ill try that right now!
