### ISSUE TITLE
Feature request: imphash for Import hash in hash widget

### ISSUE THREAD

**Issue by dmknght** [horsicq/DIE-engine#28]
Just like the title, i think import hash can be useful sometime and it worth to be at Hash widget :D

**Comment by horsicq** [comment]
Thanks a lot for the idea. I will think about it. :)

**Comment by dmknght** [comment]
> Thanks a lot for the idea. I will think about it. :)

Thank you. Just more suggestions, trendmicro made the `telfhash` which does similar thing for ELF binaries. It is available on github and imo it is a little slow. 
And there is an article about dotnet binaries have the same imphash (i don't remember exactly the URL and information) so somebodies created new method to create imphash-like. Just more information that i think it is useful if you want to add imphash :D

**Comment by horsicq** [comment]
Ok. Thanks for the info. I will take a look and add it to DiE. :)

**Comment by horsicq** [comment]
It will be in the next version.
