### ISSUE TITLE
Please release appimage

### ISSUE THREAD

**Issue by MariasStory** [horsicq/DIE-engine#29]
An .appimage as one file would be good to have.
Also it might solve the dependency problem on Ubuntu 18

**Comment by horsicq** [comment]
Thanks for the idea! I will try it. Do you have Ubuntu 18.04? Did you try to create deb package from sources?

Install packages:

sudo apt-get install qtbase5-dev -y
sudo apt-get install qtscript5-dev -y
sudo apt-get install qttools5-dev-tools -y
sudo apt-get install git -y
sudo apt-get install build-essential -y
git clone --recursive https://github.com/horsicq/DIE-engine.git

Run build script: bash -x build_dpkg.sh

**Comment by MariasStory** [comment]
I got the .deb file in docker. I could not find the executable in the .deb file or on the system after installation.
```
sudo docker run -it --rm -v ~/host:/host ubuntu:18.04 /bin/bash
apt update
apt-get install qtbase5-dev -y
apt-get install qtscript5-dev -y
apt-get install qttools5-dev-tools -y
apt-get install git -y
apt-get install build-essential -y
apt install git -y
apt install sudo -y
git clone --recursive https://github.com/horsicq/DIE-engine.git
cd DIE-engine/
bash -x build_dpkg.sh
cp release/die_*_amd64.deb /host/

cd release
apt install libqt5scripttools5 libqt5script5
dpkg -i die_3.02-20210424_amd64.deb
```

**Comment by horsicq** [comment]
Thanks a lot for the testing. I will check it.

**Comment by horsicq** [comment]
I checked and made changes in script and sources.

Could you try again. 

sudo apt-get install qtbase5-dev -y
sudo apt-get install qtscript5-dev -y
sudo apt-get install qttools5-dev-tools -y
**sudo apt-get install qt5-default**
sudo apt-get install git -y
sudo apt-get install build-essential -y
git clone --recursive https://github.com/horsicq/DIE-engine.git

cd DIE-engine

Run build script: bash -x build_dpkg.sh

dpkg -i release/ die_*.deb

**die** and **diec** should be in **/usr/bin/**

**Comment by horsicq** [comment]
The AppImage will be in the next version 3.02.
