### ISSUE TITLE
DIEC_mac -database specification

### ISSUE THREAD

**Issue by enhanced** [horsicq/DIE-engine#3]
I am running DIEC_mac and can only make it read the db when the db is in the CWD as the DIEC_mac binary.  I have tried as many ways as I can think of to specify the db path using the -database option and it never works.  Please advise, examples below:

DIEC_mac * -database:/Volumes/BIGSTORE/development/Detect-It-Easy/
DIEC_mac * -database:/Volumes/BIGSTORE/development/Detect-It-Easy/db/*
DIEC_mac * -database:/Volumes/BIGSTORE/development/Detect-It-Easy/db

always with the same results, note the Invalid Signatures Database... maybe I am missing something simple...

Number of files: 3

<hash>
PE: Nothing found

<hash>
PE: Nothing found

<hash>
PE: Nothing found
Invalid signatures database! Please download signatures from https://github.com/horsicq/Detect-It-Easy/tree/master/db and put it to the application path.

**Comment by horsicq** [comment]
Thank a lot for the testing. I'll take a look.

**Comment by thiagoolmarques** [comment]
I also found this error not only for Mac but for other versions as well. I have submitted a pull request fixing this issue.

**Comment by horsicq** [comment]
Thanks a lot!
