### ISSUE TITLE
build_tools dir is empty

### ISSUE THREAD

**Issue by jimdi** [horsicq/DIE-engine#32]
build_tools\windows.cmd is not recognized as an internal or external command

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport.

Please try git clone **--recursive** https://github.com/horsicq/DIE-engine.git to download sources

**--recursive** is very important. It get all submodules.

**Comment by jimdi** [comment]
oh, i missed new submodule

this works fine for me
`git submodule update --recursive`
