### ISSUE TITLE
Version 3.02 does not open in macOS 11.3.1

### ISSUE THREAD

**Issue by zWaR** [horsicq/DIE-engine#34]
Hey there,

When opening version 3.02 in macOS 11.3.1 I am greeted with the following error:

![image](https://user-images.githubusercontent.com/4272114/120948833-14aa2b00-c711-11eb-9e3d-af6c5ab1da51.png)

The problem happens with the dmg as well as zip asset. Version 3.01 however, works just fine.

Thanks for all the hard work with this excellent tool.

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport! I will take a look.

**Comment by bbeale** [comment]
> Hey there,
> 
> When opening version 3.02 in macOS 11.3.1 I am greeted with the following error:
> 
> ![image](https://user-images.githubusercontent.com/4272114/120948833-14aa2b00-c711-11eb-9e3d-af6c5ab1da51.png)
> 
> The problem happens with the dmg as well as zip asset. Version 3.01 however, works just fine.
> 
> Thanks for all the hard work with this excellent tool.

I just confirmed the same on 11.4. 

Thanks for all your hard work @horsicq!

**Comment by horsicq** [comment]
I reuploaded packages for OSX. https://github.com/horsicq/DIE-engine/releases/tag/3.02
It should work now.

**Comment by bbeale** [comment]
Unfortunately it is still not working.

**Comment by horsicq** [comment]
> Unfortunately it is still not working.

Thanks for testing.

**Comment by horsicq** [comment]
https://github.com/horsicq/build_tools/blob/master/OSX_NO_CERT.md
