### ISSUE TITLE
[Request] AppImage Version Command line Argument

### ISSUE THREAD

**Issue by zero77** [horsicq/DIE-engine#35]
Can you please add a command line argument like -v output `v3.02` to quickly show the current version from the terminal.
Thanks

**Comment by horsicq** [comment]
Thanks for thd idea  I will add this feuture.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.03b

**Comment by zero77** [comment]
Thanks
