### ISSUE TITLE
Console version improvements

### ISSUE THREAD

**Issue by useretail** [horsicq/DIE-engine#37]
Console version or diec has only some basic functionality in comparison to GUI version
IMO, needs improvements to match GUI version.

> diec -de mydll.dll
> Total 7.7776: packed
>  0|PE Header|0|4096|6.83707: packed
>  1|Section(1)['UPX1']|1024|465920|7.79049: packed
>  2|Section(2)['.rsrc']|466944|5120|4.47426: not packed
>  3|Overlay|472064|512|0.156521: not packed

**Comment by horsicq** [comment]
Thanks for the idea. I will  think about it!

**Comment by horsicq** [comment]
Added new features.
