### ISSUE TITLE
Die corrupts input binary when working with overlay

### ISSUE THREAD

**Issue by greenozon** [horsicq/DIE-engine#39]
Used this tool:
![image](https://user-images.githubusercontent.com/765343/129441061-e9ab1b59-dfbc-4cc9-bf76-edb2ff8e3231.png)

Opened some exe inside it
Clicked "Overlay" button
CTRL+A
CTRL+D
save

Result: input file is corrupted, saved file is different after each save

Expected behaviour:

input file stays same
overlay file written in correct way

Input file:
[test1.zip](https://github.com/horsicq/DIE-engine/files/6986212/test1.zip)

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will fix it as soon as possible.

**Comment by horsicq** [comment]
Fixed:

https://github.com/horsicq/Formats/compare/81a81f34f171466de1ddaf556f5469aa0319b1b8...89d060118b4217f94fc9443d4a59cd45fb9ab99c#diff-36fc57d2596db4a72f27759a071fd7d740a1a59434c3a307dc93a5809dc86e6b

**Comment by greenozon** [comment]
Hi @horsicq 
Thanks for upser fast fix,
as far as I understand this is a critical bug - it writes data into input file instead of reading from it

Could it be announced when do you plan to release Die binary release?

**Comment by horsicq** [comment]
[die_win32_portable__portable_3.03.zip](https://github.com/horsicq/DIE-engine/files/7025249/die_win32_portable__portable_3.03.zip)
[die_win64_portable__portable_3.03.zip](https://github.com/horsicq/DIE-engine/files/7025250/die_win64_portable__portable_3.03.zip)
[die_winxp_portable__portable_3.03.zip](https://github.com/horsicq/DIE-engine/files/7025251/die_winxp_portable__portable_3.03.zip)

**Comment by horsicq** [comment]
I will release new version in 1-2 months. It is a beta version.
