### ISSUE TITLE
Search for strings window issue

### ISSUE THREAD

**Issue by greenozon** [horsicq/DIE-engine#42]
While playing with strings searching window I"ve encountered some strange issue
if you leave just  "C Strings" after some previous search - it ignores your request and does nothing

![image](https://user-images.githubusercontent.com/765343/129447359-db23a41a-5d32-4650-9c7d-55f536e9239e.png)

Please validate that this checkbox is active or maybe it depends on other checkboxes?

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. I will fix it.

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/DIE-engine/commit/67d2cb275659065524ef8626ee3cc5da68031695
