### ISSUE TITLE
Strings filtering issue in Strings window

### ISSUE THREAD

**Issue by greenozon** [horsicq/DIE-engine#44]
what is the proper way to filter strings on the pattern

example:
![image](https://user-images.githubusercontent.com/765343/129447602-df1c3f88-006d-47fd-8fdc-7f2a09895770.png)

if I put " pattern - all is fine
if I add "{
to pattern - strings are filtered out, expected to see those, which have pattern inside
eg:
![image](https://user-images.githubusercontent.com/765343/129447646-3bfe6e77-fb2a-4ec8-a161-e564b5e3f674.png)

**Comment by horsicq** [comment]
I think you need regexp filter. I will add it soon.

**Comment by greenozon** [comment]
Well, I did not have regexp in my mind, just looking for strings as is

so the question is - having some strings with "... "{... " inside it (as on above example)
 why can't I find the "{  substring in it?

**Comment by horsicq** [comment]
Hmm. Ok It seems like a bug. I will check it.

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/DIE-engine/commit/67d2cb275659065524ef8626ee3cc5da68031695
