### ISSUE TITLE
Crash when scanning

### ISSUE THREAD

**Issue by megabugman** [horsicq/DIE-engine#53]
not sure if this is file specific (see below), or a general issue.
scanning crashes DIE:

![crash2](https://user-images.githubusercontent.com/17204819/136115014-17598f4c-eb70-4a72-b2e2-0deaf9bc47f9.gif)

sample use 0000 to unpack:
http://aalapshah.in/download/qipressportable_password0000.zip

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will take a look.

**Comment by horsicq** [comment]
I fixed it. The new version of DiE will be in a few days.
