### ISSUE TITLE
Create release source code with full submodules's source

### ISSUE THREAD

**Issue by dmknght** [horsicq/DIE-engine#57]
Hello! I should create this issue long time ago but i forgot about this.
Debian packaging has a tool called `uscan` which allows maintainer download new release's source code from github to build new version. However, it doesn't have something like `git clone --recursive` to get all source code from all submodules. So it would be nice if you can do that in next release.

**Comment by horsicq** [comment]
Thanks a lot for the idea! I will release new version(3.03) in one week. It will be with full source code.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.03

**Comment by dmknght** [comment]
> https://github.com/horsicq/DIE-engine/releases/tag/3.03

Hello! Thank you I'm building it right now

**Comment by dmknght** [comment]
The full source code was downloaded. The issue can be closed now :D thank you a lot

**Comment by dmknght** [comment]
![image](https://user-images.githubusercontent.com/29118926/141671360-93065104-80e6-4f89-ac60-219365557d7c.png)
It build successfully. I think I have to edit the build rule for the die-engine data but everything else is good. Thanks a lot :D

**Comment by horsicq** [comment]
Thank you for your supporting! :)
