### ISSUE TITLE
change md5 as default hash type

### ISSUE THREAD

**Issue by qux-bbb** [horsicq/DIE-engine#65]
DIE use md4 as default hash type.  
![hash_method](https://user-images.githubusercontent.com/18598419/158094091-5f7b4419-c180-4ba8-b6e3-9b82d6c13aae.png)  
In many times, people want to get md5 value. Also, the shape of md4 and md5 are similar, and someone maybe copy a md4 value rather than md5 value.  
So is it possible to change md5 as default hash type?

**Comment by horsicq** [comment]
Good idea. Thanks. I will make it

**Comment by horsicq** [comment]
Fixed. MD5 is default now,
