### ISSUE TITLE
diec status code is 0 even on error

### ISSUE THREAD

**Issue by sy6sy2** [horsicq/DIE-engine#68]
Just noticed that if you run `diec -j ./foo` and `foo` file does not exist then you obtain `Cannot find: ./foo` but the exit code of `diec` is 0.

I expect the status code to be other than 0 because we have an error here.

**Comment by horsicq** [comment]
Thanks for the idea. I will take a look.

**Comment by horsicq** [comment]
Ok. It will be in the next version.

**Comment by sy6sy2** [comment]
Tested on version 3.08. Fixed. thanks!
