### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by modz2014** [horsicq/DIE-engine#70]
hey i was wondering if you could fix the update button to download files from github instead of loading the website would make it alot nicer

**Comment by horsicq** [comment]
Thanks a lot for the good idea! I will think about it.

**Comment by modz2014** [comment]
yer looks a lot cleaner aye i also was thinking of updating this as well

**Comment by modz2014** [comment]
suggestion on making the context menu for new using IExplorerCommand

**Comment by horsicq** [comment]
Thanks a lot for the idea!

**Comment by modz2014** [comment]
seeing Microsoft will be getting rid of the old context menu in the future

**Comment by modz2014** [comment]
the only way to do this for msix packages spare packages ect

**Comment by modz2014** [comment]
i created an example for ILSpy if you want to use that

**Comment by horsicq** [comment]
Thank you! I will take a look.

**Comment by modz2014** [comment]
know worries the only way is to use appx packages hopefully microsoft fix it so you dont have too

**Comment by modz2014** [comment]
let me know when its implemented

**Comment by modz2014** [comment]
hey this might help you with the location of your program you will need to package the shell context as msix package hope this help's you https://github.com/modz2014/ILSpyContextMenu/blob/f5ab8d5b2e2a8b78e6ece80f6010eee82c7db35e/ContextMenuImplementation/dllmain.cpp#L199-L293

**Comment by modz2014** [comment]
hey @horsicq any update on this

**Comment by horsicq** [comment]
Hello! I am working on it!

**Comment by modz2014** [comment]
ok no worries hope here from you soon about it would be nice instead of clicking things twice

**Comment by horsicq** [comment]
Btw I sent you a message in Discord

**Comment by modz2014** [comment]
i didn't receive it

**Comment by modz2014** [comment]
@horsicq i discord you some more suggestions that i was working on

**Comment by modz2014** [comment]
.

Repository: [modz2014/DieShell](https://github.com/modz2014/DieShell)
