### ISSUE TITLE
Zig binaries are unknown

### ISSUE THREAD

**Issue by kassane** [horsicq/DIE-engine#75]
ref.: #74 
cc: @horsicq 

Currently only the linker is identified. However, the compiler continues without information.
The signature script works on PE, but not for Linux and MacOS.
Currently zig uses llvm-ld on windows and linux. However, on MacOS there is a new linker under development called [zld](https://github.com/kubkon/zld).

<details>
<summary>Preview</summary>

- MacOS [x86_64]
![die_zig macos](https://user-images.githubusercontent.com/6756180/203607680-948159c0-2bcd-42aa-b682-9643a5067776.jpg)

- Linux (Musl) [x86_64]
![die_zig linux](https://user-images.githubusercontent.com/6756180/203607679-f3bfb597-e020-49ee-bea5-ff63e5bcdbfa.jpg)

- MacOS [ARM64]
![die_zig arm64_macos](https://user-images.githubusercontent.com/6756180/203607674-6d218262-fc12-47fc-84ad-f6490f815d9e.jpg)

- Windows [x86_64]
![die_zig win](https://user-images.githubusercontent.com/6756180/203607682-75ede735-f934-4339-998c-7009fe918739.jpg)
</details>

**Comment by kassane** [comment]
@horsicq 
[zig_binaries.tar.gz](https://github.com/horsicq/DIE-engine/files/10078892/zig_binaries.tar.gz)

**Comment by horsicq** [comment]
Fixed
