### ISSUE TITLE
Compiling DIE GUI fails on Ubuntu 20.4.5 ARM64

### ISSUE THREAD

**Issue by dirk-fr** [horsicq/DIE-engine#77]
I know ARM64 is not supported yet - still had to try. Maybe you find this helpful.
release_version = 3.0.7

When compiling DIE on Ubuntu 20.4.5 ARM64, the make command for the gui_source sub-dir errors out:

../FormatWidgets/PE/peprocessdata.cpp: In member function ‘virtual void PEProcessData::_process()’:
../FormatWidgets/PE/peprocessdata.cpp:882:25: error: ‘struct SpecAbstract::SCAN_OPTIONS’ has no member named ‘varInfo’
  882 |                 options.varInfo = listResources.at(i).irin[0].nID;
      |                         ^~~~~~~
make: *** [Makefile:37271: peprocessdata.o] Error 1

Indeed there seems to be no "varInfo" member in the SCAB_OPTIONS struct.
Commenting out line 882 in "peprocessdata.cpp" seems to resolve the issue - haven't seen any negative impact from doing that yet...

Dirk

**Comment by horsicq** [comment]
Wow! Thank you for testing it on ARM! I added this varinfo yesterday  i guess you could just make fresh "git clone" to resolve this problem. Or just comment it as you did.

**Comment by horsicq** [comment]
I will add ARM in the future. Are you using Ubuntu ARM64 on Raspberry Pi?

**Comment by dirk-fr** [comment]
Working on a MacBook Air M2 running Ubuntu 20.4.5 ARM in a VMWare Fusion machine.
So far DIE seems to compile (using automate) fine - had to manually install qt5script for some reason, otherwise no issues.
If you have a test-suite to validate more formally, feel free to share and I'll run the tests.

**Comment by horsicq** [comment]
Great! Thank you!
