### ISSUE TITLE
DLL version?

### ISSUE THREAD

**Issue by CCRDude** [horsicq/DIE-engine#82]
Hi,

Some years ago, I was playing around with creating a plugin for DetectItEasy for [FileAlyzer](https://www.safer-networking.org/products/filealyzer/). Back then, there was a `diedll.dll` including C headers that made it quite easy.

Putting in a new db folder works only partially (results partially without names).

Is there a chance we can get the DLL version back? With a backend simply tied to an UI and a console, tying it into a library might be simple?

**Comment by horsicq** [comment]
Hello! Thanks a lot for the suggestion. I will make the dll again.

**Comment by horsicq** [comment]
https://github.com/horsicq/die_library
