### ISSUE TITLE
Update issue: 201-> 202

### ISSUE THREAD

**Issue by greenozon** [horsicq/DIE-engine#9]
Check for update lead to this page:  http://ntinfo.biz/index.php/detect-it-easy

and it shows : 

Forbidden
You don't have permission to access /index.php/detect-it-easy on this server.
Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. It has to work now.
